// Write the artifact set that downstream tests/scripts consume:
//
//   <artifacts>/network.json   — full NetworkArtifactDoc (machine-readable)
//   <artifacts>/addresses.ts   — typed TS exports (one constant per chain)
//   <artifacts>/.env           — shell-friendly KEY=value lines
//
// Naming: chain names are upper-snake-cased for env vars. The C-Chain is
// emitted as the literal prefix `C_CHAIN` regardless of the handle's `.name`
// field so tooling can rely on a stable key.

import { mkdir, writeFile } from "node:fs/promises";
import * as path from "node:path";

import type {
  ChainHandle,
  FundedAccount,
  L1Handle,
  NetworkArtifactDoc,
  NetworkArtifacts,
  NetworkHandle,
} from "../types.js";
import { paths as networkPaths } from "../internal/config.js";
import { DEFAULT_RELAYER_ADDRESS } from "../icm/relayer.js";

/**
 * Subset of NetworkHandle that we actually need to write artifacts. Lets
 * callers invoke this before the full NetworkHandle is assembled.
 */
export interface ArtifactsInput {
  cChain: ChainHandle;
  l1s: L1Handle[];
  funded: FundedAccount;
  /**
   * Relayer EOA. Defaults to the deterministic key the orchestrator boots
   * icm-relayer with (Anvil[0]).
   */
  relayerAddress?: import("viem").Address;
}

/** Upper-snake-case a chain name for env-var prefixes. */
export function envPrefix(name: string): string {
  return name.replace(/[^A-Za-z0-9]+/g, "_").toUpperCase();
}

/** Camel-case a chain name for TS identifiers (`my-l1` → `myL1`). */
export function tsIdentifier(name: string): string {
  const parts = name.split(/[^A-Za-z0-9]+/).filter(Boolean);
  if (parts.length === 0) return "chain";
  const first = parts[0]!.toLowerCase();
  const rest = parts
    .slice(1)
    .map((p) => p[0]!.toUpperCase() + p.slice(1).toLowerCase());
  return [first, ...rest].join("");
}

export function buildArtifactDoc(input: ArtifactsInput): NetworkArtifactDoc {
  return {
    funded: input.funded,
    relayer: { address: input.relayerAddress ?? DEFAULT_RELAYER_ADDRESS },
    cChain: input.cChain,
    l1s: input.l1s,
  };
}

function renderAddressesTs(input: ArtifactsInput): string {
  const lines: string[] = [
    "// AUTOGENERATED by tmpnetjs. Do not edit by hand.",
    "// Re-run `tmpnetjs up` to refresh.",
    "",
    'import type { Address, Hex } from "viem";',
    "",
    "export const FUNDED_ACCOUNT = {",
    `  address: ${JSON.stringify(input.funded.address)} as Address,`,
    `  privateKey: ${JSON.stringify(input.funded.privateKey)} as Hex,`,
    "} as const;",
    "",
    "// EOA the icm-relayer delivers messages with, on every chain. Pin it in",
    "// allowedRelayerAddresses to exercise relayer allowlists.",
    "export const RELAYER = {",
    `  address: ${JSON.stringify(input.relayerAddress ?? DEFAULT_RELAYER_ADDRESS)} as Address,`,
    "} as const;",
    "",
  ];

  const renderChain = (varName: string, c: ChainHandle | L1Handle): string[] => {
    const isL1 = "subnetId" in c;
    return [
      `export const ${varName} = {`,
      `  name: ${JSON.stringify(c.name)},`,
      `  evmChainId: ${c.evmChainId},`,
      `  blockchainId: ${JSON.stringify(c.blockchainId)},`,
      `  rpcUrl: ${JSON.stringify(c.rpcUrl)},`,
      ...(c.wsUrl ? [`  wsUrl: ${JSON.stringify(c.wsUrl)},`] : []),
      `  teleporter: ${JSON.stringify(c.teleporter)} as Address,`,
      `  teleporterRegistry: ${JSON.stringify(c.teleporterRegistry)} as Address,`,
      ...(isL1
        ? [
            `  subnetId: ${JSON.stringify((c as L1Handle).subnetId)},`,
            `  validatorManager: ${JSON.stringify(
              (c as L1Handle).validatorManager,
            )} as Address,`,
          ]
        : []),
      "} as const;",
      "",
    ];
  };

  lines.push(...renderChain("C_CHAIN", input.cChain));
  for (const l1 of input.l1s) {
    lines.push(...renderChain(tsIdentifier(l1.name).toUpperCase(), l1));
  }

  // Aggregate index for convenience.
  const allRefs = ["C_CHAIN", ...input.l1s.map((l1) => tsIdentifier(l1.name).toUpperCase())];
  lines.push(`export const CHAINS = [${allRefs.join(", ")}] as const;`);
  lines.push("");

  return lines.join("\n");
}

function renderEnvFile(input: ArtifactsInput): string {
  const lines: string[] = [
    "# AUTOGENERATED by tmpnetjs. Do not edit by hand.",
    `FUNDED_ADDRESS=${input.funded.address}`,
    `FUNDED_KEY=${input.funded.privateKey}`,
    `RELAYER_ADDRESS=${input.relayerAddress ?? DEFAULT_RELAYER_ADDRESS}`,
    "",
  ];

  const renderChain = (prefix: string, c: ChainHandle | L1Handle): void => {
    lines.push(`${prefix}_NAME=${c.name}`);
    lines.push(`${prefix}_EVM_CHAIN_ID=${c.evmChainId}`);
    lines.push(`${prefix}_BLOCKCHAIN_ID=${c.blockchainId}`);
    lines.push(`${prefix}_RPC=${c.rpcUrl}`);
    if (c.wsUrl) lines.push(`${prefix}_WS=${c.wsUrl}`);
    lines.push(`${prefix}_TELEPORTER=${c.teleporter}`);
    lines.push(`${prefix}_TELEPORTER_REGISTRY=${c.teleporterRegistry}`);
    if ("subnetId" in c) {
      lines.push(`${prefix}_SUBNET_ID=${(c as L1Handle).subnetId}`);
      lines.push(`${prefix}_VALIDATOR_MANAGER=${(c as L1Handle).validatorManager}`);
    }
    lines.push("");
  };

  renderChain("C_CHAIN", input.cChain);
  for (const l1 of input.l1s) {
    renderChain(envPrefix(l1.name), l1);
  }
  return lines.join("\n");
}

/**
 * Write all three artifact files. Returns the paths via NetworkArtifacts.
 * `workDir` is the network work directory (same one passed to `paths()`).
 */
export async function writeArtifacts(
  input: ArtifactsInput,
  workDir: string,
): Promise<NetworkArtifacts> {
  const p = networkPaths(workDir);
  await mkdir(p.artifacts, { recursive: true });

  const doc = buildArtifactDoc(input);
  const networkJson = path.join(p.artifacts, "network.json");
  const addressesTs = path.join(p.artifacts, "addresses.ts");
  const envFile = path.join(p.artifacts, ".env");

  await Promise.all([
    writeFile(networkJson, JSON.stringify(doc, null, 2) + "\n", "utf8"),
    writeFile(addressesTs, renderAddressesTs(input), "utf8"),
    writeFile(envFile, renderEnvFile(input), "utf8"),
  ]);

  return { dir: p.artifacts, networkJson, addressesTs, envFile };
}

/** Convenience overload: take a full NetworkHandle. */
export async function writeArtifactsForNetwork(
  network: NetworkHandle,
  workDir: string,
): Promise<NetworkArtifacts> {
  return writeArtifacts(
    { cChain: network.cChain, l1s: network.l1s, funded: network.funded },
    workDir,
  );
}
